# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: mypy-typecheck
        name: MyPy Typecheck
        entry: make typecheck
        language: system
      - id: unittest
        name: Python Unit Tests
        entry: make test-python
        language: system
      - id: freeze-requirements
        name: Freeze Requirements
        entry: make freeze
        language: system
